import { createConfig } from "ponder";
import deployment from "./deployment.json";

// deployment.json is generated by ../scripts/deploy.ts on every deploy
// (contract addresses + ABIs + the block to start indexing from).
export default createConfig({
  database: {
    kind: "postgres",
    connectionString: process.env.DATABASE_URL,
  },
  chains: {
    local: {
      id: deployment.chainId,
      // From inside Docker the chain is the `hardhat` service; overridable via env.
      rpc: process.env.PONDER_RPC_URL ?? "http://hardhat:8545",
      // Required for local dev chains that reset (no durable RPC cache).
      disableCache: true,
    },
  },
  contracts: {
    Collectible: {
      abi: deployment.collectible.abi,
      chain: "local",
      address: deployment.collectible.address as `0x${string}`,
      startBlock: deployment.startBlock,
    },
    Marketplace: {
      abi: deployment.marketplace.abi,
      chain: "local",
      address: deployment.marketplace.address as `0x${string}`,
      startBlock: deployment.startBlock,
    },
  },
});
