import { network } from "hardhat";
import { writeFileSync } from "node:fs";
import { join } from "node:path";

// Deploy the on-chain core to the connected network, seed it with sample
// collectibles spanning all four categories, list a few, and write the
// frontend's config.js (addresses + ABIs). Run with:
//   hardhat run scripts/deploy.ts --network localhost
const { ethers } = await network.connect();

const [deployer] = await ethers.getSigners();
const net = await ethers.provider.getNetwork();
console.log(`Network chainId=${net.chainId}, deployer=${deployer.address}`);

// ---- deploy ----
const PLATFORM_FEE_BPS = 250n; // 2.5%
const collectible = await ethers.deployContract("Collectible", [deployer.address]);
await collectible.waitForDeployment();
const marketplace = await ethers.deployContract("Marketplace", [
  deployer.address,
  deployer.address,
  PLATFORM_FEE_BPS,
]);
await marketplace.waitForDeployment();

const collectibleAddr = await collectible.getAddress();
const marketplaceAddr = await marketplace.getAddress();
console.log(`Collectible: ${collectibleAddr}`);
console.log(`Marketplace: ${marketplaceAddr}`);

// ---- seed: mint sample items (metadata served at :8080/metadata/<id>.json) ----
const METADATA_BASE = process.env.METADATA_BASE_URL ?? "http://localhost:8080/metadata";
const SAMPLE_COUNT = 8; // ids 0..7 — see metadata/*.json
for (let id = 0; id < SAMPLE_COUNT; id++) {
  await (await collectible.mintItem(`${METADATA_BASE}/${id}.json`)).wait();
}
console.log(`Minted ${SAMPLE_COUNT} sample items to ${deployer.address}`);

// ---- list a few so the marketplace is not empty (id -> price in ETH) ----
await (await collectible.setApprovalForAll(marketplaceAddr, true)).wait();
const LISTINGS: Array<[number, string]> = [
  [0, "0.05"], // Charizard card
  [2, "0.12"], // digital art
  [4, "0.40"], // wine
  [6, "0.85"], // antique
];
for (const [id, price] of LISTINGS) {
  await (await marketplace.listItem(collectibleAddr, id, ethers.parseEther(price))).wait();
}
console.log(`Listed ${LISTINGS.length} items`);

// ---- write frontend/config.js ----
const config = `// AUTO-GENERATED by scripts/deploy.ts — do not edit by hand.
export const CHAIN_ID = ${net.chainId};
export const RPC_URL = "http://localhost:8545";
export const METADATA_BASE = "${METADATA_BASE}";
export const COLLECTIBLE_ADDRESS = "${collectibleAddr}";
export const MARKETPLACE_ADDRESS = "${marketplaceAddr}";
export const COLLECTIBLE_ABI = ${collectible.interface.formatJson()};
export const MARKETPLACE_ABI = ${marketplace.interface.formatJson()};
`;
writeFileSync(join(process.cwd(), "frontend", "config.js"), config);
console.log("Wrote frontend/config.js");
