// Mint the ai-items.json catalog, distributing ownership across 3 accounts
// (#0, #2, #3) and listing most of them. tokenURIs point at metadata/<id>.json
// (generated by scripts/gen-ai-images.mjs).
//   hardhat run scripts/mint-batch.ts --network localhost
import { network } from "hardhat";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const { ethers } = await network.connect();
const dep = JSON.parse(readFileSync(join(process.cwd(), "indexer", "deployment.json"), "utf8"));
const items = JSON.parse(readFileSync(join(process.cwd(), "scripts", "ai-items.json"), "utf8"));
const BASE = process.env.METADATA_BASE_URL || "http://100.70.161.82:8080/metadata";

const signers = await ethers.getSigners();
const owners = [signers[0], signers[2], signers[3]]; // 3 owner accounts
const nft = dep.collectible.address;
const mkt = dep.marketplace.address;

const reader = new ethers.Contract(nft, dep.collectible.abi, signers[0]);
const start = Number(await reader.totalMinted());
console.log(`start id ${start}, minting ${items.length} items across ${owners.length} owners`);

// one-time marketplace approval per owner
for (const o of owners) {
  const c = new ethers.Contract(nft, dep.collectible.abi, o);
  if (!(await c.isApprovedForAll(o.address, mkt))) {
    await (await c.setApprovalForAll(mkt, true)).wait();
  }
}

const prices = ["0.03", "0.05", "0.08", "0.12", "0.2", "0.35", "0.5", "0.8", "1.2"];
let listed = 0;
for (let i = 0; i < items.length; i++) {
  const id = start + i;
  const owner = owners[i % owners.length];
  const c = new ethers.Contract(nft, dep.collectible.abi, owner);
  const m = new ethers.Contract(mkt, dep.marketplace.abi, owner);

  await (await c.mintItem(`${BASE}/${id}.json`)).wait();
  // list ~90% (keep every 10th unlisted so some are "owned, not for sale")
  let tag = "(unlisted)";
  if (i % 10 !== 0) {
    const price = prices[id % prices.length];
    await (await m.listItem(nft, id, ethers.parseEther(price))).wait();
    tag = `listed ${price} ETH`;
    listed++;
  }
  console.log(`  #${id} -> ${owner.address.slice(0, 8)}… ${items[i].category.padEnd(10)} ${tag}`);
}
console.log(`done: minted ${items.length}, listed ${listed}`);
